version: "3.7"
services:
  mysql1:
    image: mysql:latest
    container_name: mysql1
    volumes:
      - ./mysql1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password1
    ports:
      - 3309:3306
  mysql2:
      image: mysql:latest
      container_name: mysql2
      volumes:
        - ./mysql2:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: password2
      ports:
      - 3308:3306
  grafana:
    image: grafana/grafana
    ports:
      - 8080:3000
    environment:
      GF_INSTALL_PLUGINS: percona-percona-app
      
  prom_mysql_exporter:
    image: prom/mysqld-exporter
    links:
      - mysql1
    ports:
      - 9104:9104
    environment:
      DATA_SOURCE_NAME: root:password1@(mysql1:3306)/vm1
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    links:
      - prom_mysql_exporter
    ports:
      - 9090